services:
  - type: web
    name: vegetable-inventory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import db; db.create_all()"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vegetable-inventory-db
          property: connectionString

databases:
  - name: vegetable-inventory-db
    databaseName: vegetable_inventory
    user: vegetable_inventory_user 