services:
  - type: web
    name: vegetable-inventory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p templates static
      cp -r templates/* templates/ || true
      cp -r static/* static/ || true
      export FLASK_APP=wsgi.py
      export FLASK_ENV=production
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      python -c "from app import db; db.create_all()"
      python create_admin.py
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vegetable-inventory-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_DEBUG
        value: "0"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "DEBUG"

databases:
  - name: vegetable-inventory-db
    databaseName: vegetable_inventory
    user: vegetable_inventory_user 