services:
  - type: web
    name: vegetable-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py 